apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: hdfs-datanode-custom
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hdfs-datanode
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: whether_add_pod
      describedObject:
        apiVersion: apps/v1
        kind: Deployment
        name: hpa-exporter-deployment
      target:
        kind: Value
        value: 1
  behavior:
    scaleDown:
      # stabilizationWindowSeconds: 300
      selectPolicy: Disabled   # 禁止缩容
    scaleUp:
      stabilizationWindowSeconds: 100
      policies:
        - type: Pods
          value: 3
          periodSeconds: 20
      selectPolicy: Max

