apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hdfs-datanode
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: hdfs-datanode
  endpoints:
  - interval: 15s
    port: pexport
    path: /metrics
