apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  namespace: monitoring
spec:
  type: NodePort
  selector:
    name: hdfs-namenode
  ports:
    - name: rpc
      port: 9000
      targetPort: 9000
    - name: http
      port: 50070
      targetPort: 50070
      nodePort: 32007
    - name: ssh
      port: 31822
      targetPort: 31822

---

kind: Service
apiVersion: v1
metadata:
  name: hdfs-datanode
  namespace: monitoring
  labels:
    name: hdfs-datanode
spec:
  selector:
    name: hdfs-datanode
  ports:
  - name: pexport
    port: 10318
