apiVersion: v1
kind: Service
metadata:
  name: tikv-service
  namespace: monitoring
  labels:
    name: tikv-service
    app.kubernetes.io/component: tikv
spec:
  type: NodePort
  ports:
    - name: metrics
      port: 20180
      targetPort: 20180
      nodePort: 20180
  selector:
    app.kubernetes.io/component: tikv

