apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: advanced-tidb-tikv
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: tikv
  endpoints:
  - interval: 15s
    targetPort: 20180
    path: /metrics
