apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: advanced-tidb-tikv
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: tikv-service
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
