apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hdfs-datanode
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hdfs-datanode
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: disk_utilization
      target: 
        type: AverageValue
        averageValue: 0.5
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      # stabilizationWindowSeconds: 300
      selectPolicy: Disabled   # 禁止缩容
    scaleUp:
      stabilizationWindowSeconds: 100
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
      selectPolicy: Min

