apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  namespace: monitoring
spec:
  serviceName: "hdfs-datanode"
  replicas: 3
  selector:
    matchLabels:
      name: hdfs-datanode
  template:
    metadata:
      labels:
        name: hdfs-datanode
    spec:
      containers:
      - name: hdfs-datanode
        image: jinbozi/hdfs:0.6
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9000
          - containerPort: 50070
          - name: pexport
            containerPort: 10318
        resources:
          requests:
            memory: "1000Mi"
            cpu: "200m"
          limits:
            memory: "2000Mi"
            cpu: "500m"
        volumeMounts:
          - name: hdfs
            mountPath: /custom/hdfs_dir
        env:
          - name: HADOOP_NODE_TYPE
            value: datanode
          - name: HDFS_MASTER_SERVICE
            valueFrom:
              configMapKeyRef:
                name: hdfs-conf
                key: HDFS_MASTER_SERVICE
          - name: HDFS_REP
            valueFrom:
              configMapKeyRef:
                name: hdfs-conf
                key: HDFS_REP
  volumeClaimTemplates:
  - metadata:
      name: hdfs
    spec:
      accessModes: ["ReadWriteOnce"]
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
      storageClassName: csi-lvm
