apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-hpa-exporter-deployment
  namespace: monitoring
  labels:
    k8s-app: hdfs-hpa-exporter
spec:
  selector:
    matchLabels:
      k8s-app: hdfs-hpa-exporter
  template:
    metadata:
      labels:
        k8s-app: hdfs-hpa-exporter
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: hdfs-hpa-exporter
          image: aliuchangjie/hpa_exporter:latest
          command: [ "/usr/bin/hpa_exporter" ]
          args: ["-statefulset", "hdfs-datanode", "-namespace", "monitoring"]
          ports:
            - containerPort: 30001  # 用于暴露监控的指标数据
              protocol: TCP
            - containerPort: 30002  # 用于暴露pv_server的接口
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  # hdfs-hpa-exporter-service在 pv_collector的main.go中引用到
  name: hdfs-hpa-exporter-service
  namespace: monitoring
  labels:
    name: hdfs-hpa-exporter-service
spec:
  type: NodePort
  ports:
    - name: whether-add-pod-port
      port: 30001
      targetPort: 30001
      nodePort: 31111
    - name: pv-server
      port: 30002
      targetPort: 30002
  selector:
    k8s-app: hdfs-hpa-exporter

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hdfs-hpa-exporter-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: hdfs-hpa-exporter-service
  endpoints:
    - interval: 15s
      port: whether-add-pod-port
      path: /metrics

---

# reference: https://github.com/fabric8io/fabric8/issues/6840
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hpa-exporter-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
