apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-exporter-deployment
  namespace: monitoring
  labels:
    k8s-app: hpa-exporter
spec:
  selector:
    matchLabels:
      k8s-app: hpa-exporter
  template:
    metadata:
      labels:
        k8s-app: hpa-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: hpa-exporter
        image: aliuchangjie/hpa_exporter
        command: [ "/usr/bin/hpa_exporter" ]
        args: ["-statefulset", "hdfs-datanode", "-namespace", "monitoring"]
        ports:
        - containerPort: 30001  # 用于暴露监控的指标数据
          protocol: TCP
        - containerPort: 30002  # 用于暴露pv_server的接口
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: hpa-exporter-service
  namespace: monitoring
  labels:
    name: hpa-exporter-service
spec:
  type: NodePort
  ports:
  - name: whether-add-pod-port
    port: 30001
    targetPort: 30001
    nodePort: 31111
  - name: pv-server
    port: 30002
    targetPort: 30002
  selector:
    k8s-app: hpa-exporter

---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hpa-exporter-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: hpa-exporter-service
  endpoints:
    - interval: 15s
      port: whether-add-pod-port
      path: /metrics

---

# reference: https://github.com/fabric8io/fabric8/issues/6840
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: hpa-exporter-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
