apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
spec:
  type: ClusterIP
  selector:
    name: hdfs-namenode
  ports:
    - port: 8030
      name: yarn1
    - port: 8031
      name: yarn2
    - port: 8032
      name: yarn-rpc
    - port: 8033
      name: yarn3
    - port: 9000
      name: hdfs-rpc
    - port: 19888
      name: map-reduce

---

apiVersion: v1
kind: Service
metadata:
  name: hdfs-show
spec:
  type: NodePort
  selector:
    name: hdfs-namenode
  ports:
    - name: hdfs-web
      port: 50070
      targetPort: 50070
      nodePort: 30070
    - name: yarn-web
      port: 8088
      targetPort: 8088
      nodePort: 30088
    - name: promethues
      port: 10318
      targetPort: 10318
      nodePort: 30318

---

apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
spec:
  clusterIP: None
  selector:
    name: hdfs-datanode
  ports:
    - port: 8040
      name: yarn-node0
    - port: 8041
      name: yarn-node1
    - port: 8042
      name: yarn-node-web

---

apiVersion: v1
kind: Service
metadata:
  name: hdfs-pexport
spec:
  type: NodePort
  selector:
    name: hdfs-datanode
  ports:
    - name: promethues
      port: 10318
      targetPort: 10318
      nodePort: 31318

