# https://v1-16.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#objectmetricsource-v2beta2-autoscaling
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hdfs-datanode-custom
  namespace: monitoring
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: hdfs-datanode
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Object
    object:
      metric:
        name: whether_add_pod
      describedObject:
        # kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/services/*/whether_add_pod" | jq .
        apiVersion: v1
        kind: Service
        name: hpa-exporter-service
      target:
        type: Value
        value: 1
  behavior:
    scaleDown:
      # stabilizationWindowSeconds: 300
      selectPolicy: Disabled   # 禁止缩容
    scaleUp:
#      https://kubernetes:io/zh/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics:
      stabilizationWindowSeconds: 15
#      policies:
#        - type: Pods
#          value: 1
#          periodSeconds: 20
      selectPolicy: Max

