// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pv_monitor/pv_monitor.proto

package pv_monitor

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PVRequest) Reset() {
	*x = PVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pv_monitor_pv_monitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVRequest) ProtoMessage() {}

func (x *PVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pv_monitor_pv_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVRequest.ProtoReflect.Descriptor instead.
func (*PVRequest) Descriptor() ([]byte, []int) {
	return file_pv_monitor_pv_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *PVRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PVResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PvNames []string `protobuf:"bytes,1,rep,name=pvNames,proto3" json:"pvNames,omitempty"`
}

func (x *PVResponse) Reset() {
	*x = PVResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pv_monitor_pv_monitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVResponse) ProtoMessage() {}

func (x *PVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pv_monitor_pv_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVResponse.ProtoReflect.Descriptor instead.
func (*PVResponse) Descriptor() ([]byte, []int) {
	return file_pv_monitor_pv_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *PVResponse) GetPvNames() []string {
	if x != nil {
		return x.PvNames
	}
	return nil
}

type PVNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PvNamesAndUtilization map[string]float32 `protobuf:"bytes,1,rep,name=pvNamesAndUtilization,proto3" json:"pvNamesAndUtilization,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
}

func (x *PVNamesRequest) Reset() {
	*x = PVNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pv_monitor_pv_monitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVNamesRequest) ProtoMessage() {}

func (x *PVNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pv_monitor_pv_monitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVNamesRequest.ProtoReflect.Descriptor instead.
func (*PVNamesRequest) Descriptor() ([]byte, []int) {
	return file_pv_monitor_pv_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *PVNamesRequest) GetPvNamesAndUtilization() map[string]float32 {
	if x != nil {
		return x.PvNamesAndUtilization
	}
	return nil
}

type PVNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *PVNamesResponse) Reset() {
	*x = PVNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pv_monitor_pv_monitor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PVNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVNamesResponse) ProtoMessage() {}

func (x *PVNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pv_monitor_pv_monitor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVNamesResponse.ProtoReflect.Descriptor instead.
func (*PVNamesResponse) Descriptor() ([]byte, []int) {
	return file_pv_monitor_pv_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *PVNamesResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_pv_monitor_pv_monitor_proto protoreflect.FileDescriptor

var file_pv_monitor_pv_monitor_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x76, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x76, 0x5f,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70,
	0x76, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x22, 0x1b, 0x0a, 0x09, 0x50, 0x56, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0a, 0x50, 0x56, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x70, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0xc7,
	0x01, 0x0a, 0x0e, 0x50, 0x56, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x6b, 0x0a, 0x15, 0x70, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x55,
	0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x35, 0x2e, 0x70, 0x76, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x56,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x76, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x15, 0x70, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x41, 0x6e, 0x64, 0x55, 0x74, 0x69, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x48,
	0x0a, 0x1a, 0x50, 0x76, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x41, 0x6e, 0x64, 0x55, 0x74, 0x69, 0x6c,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x29, 0x0a, 0x0f, 0x50, 0x56, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x32, 0x99, 0x01, 0x0a, 0x09, 0x50, 0x56, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x41, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x56, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x76, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x50, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x76, 0x5f,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x56, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x50, 0x56, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x76, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x2e, 0x50, 0x56, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x70, 0x76, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x50, 0x56,
	0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x17, 0x5a, 0x15, 0x70, 0x76, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x76,
	0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pv_monitor_pv_monitor_proto_rawDescOnce sync.Once
	file_pv_monitor_pv_monitor_proto_rawDescData = file_pv_monitor_pv_monitor_proto_rawDesc
)

func file_pv_monitor_pv_monitor_proto_rawDescGZIP() []byte {
	file_pv_monitor_pv_monitor_proto_rawDescOnce.Do(func() {
		file_pv_monitor_pv_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_pv_monitor_pv_monitor_proto_rawDescData)
	})
	return file_pv_monitor_pv_monitor_proto_rawDescData
}

var file_pv_monitor_pv_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pv_monitor_pv_monitor_proto_goTypes = []interface{}{
	(*PVRequest)(nil),       // 0: pv_monitor.PVRequest
	(*PVResponse)(nil),      // 1: pv_monitor.PVResponse
	(*PVNamesRequest)(nil),  // 2: pv_monitor.PVNamesRequest
	(*PVNamesResponse)(nil), // 3: pv_monitor.PVNamesResponse
	nil,                     // 4: pv_monitor.PVNamesRequest.PvNamesAndUtilizationEntry
}
var file_pv_monitor_pv_monitor_proto_depIdxs = []int32{
	4, // 0: pv_monitor.PVNamesRequest.pvNamesAndUtilization:type_name -> pv_monitor.PVNamesRequest.PvNamesAndUtilizationEntry
	0, // 1: pv_monitor.PVService.RequestPVNames:input_type -> pv_monitor.PVRequest
	2, // 2: pv_monitor.PVService.ReplyPVNames:input_type -> pv_monitor.PVNamesRequest
	1, // 3: pv_monitor.PVService.RequestPVNames:output_type -> pv_monitor.PVResponse
	3, // 4: pv_monitor.PVService.ReplyPVNames:output_type -> pv_monitor.PVNamesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pv_monitor_pv_monitor_proto_init() }
func file_pv_monitor_pv_monitor_proto_init() {
	if File_pv_monitor_pv_monitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pv_monitor_pv_monitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pv_monitor_pv_monitor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pv_monitor_pv_monitor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pv_monitor_pv_monitor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PVNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pv_monitor_pv_monitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pv_monitor_pv_monitor_proto_goTypes,
		DependencyIndexes: file_pv_monitor_pv_monitor_proto_depIdxs,
		MessageInfos:      file_pv_monitor_pv_monitor_proto_msgTypes,
	}.Build()
	File_pv_monitor_pv_monitor_proto = out.File
	file_pv_monitor_pv_monitor_proto_rawDesc = nil
	file_pv_monitor_pv_monitor_proto_goTypes = nil
	file_pv_monitor_pv_monitor_proto_depIdxs = nil
}
