apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  namespace: monitoring
spec:
  serviceName: "hdfs-namenode"
  replicas: 1
  selector:
    matchLabels:
      name: hdfs-namenode
  template:
    metadata:
      labels:
        name: hdfs-namenode
    spec:
      containers:
      - name: hdfs-namenode
        image: jinbozi/hdfs:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        ports:
          - containerPort: 9000
          - containerPort: 8032
          - containerPort: 8088
          - containerPort: 50070
          - containerPort: 31822
        securityContext:
          privileged: true
        volumeMounts:
          - name: hdfs
            mountPath: /custom/hdfs_dir
        env:
          - name: image_function
            value: "namenode|resourcemanager"
          - name: hadoop_yarn_yarn_nodemanager_resource_memory_mb # 配置默认节点内存，单位为MB
            value: "2048"
          - name: hadoop_hdfs_dfs_datanode_balance_bandwidthPerSec
            value: "20m"
  volumeClaimTemplates:
  - metadata:
      name: hdfs
    spec:
      accessModes: ["ReadWriteOnce"]
      volumeMode: Filesystem
      resources:
        requests:
          storage: 10Gi
      storageClassName: csi-lvm
